server:
  port: 8888

spring:
  application:
    name: seckill

  thymeleaf:
    # 关闭缓存
    cache: false

  redis:
    # 服务器地址
    host: 192.168.47.100
    port: 6379
    password: foxiris@qq.com
    # 默认操作的数据库
    database: 3
    timeout: 10000ms
    lettuce:
      pool:
        # 最大连接数
        max-active: 8
        # 最大阻塞等待时间
        max-wait: 10000ms
        # 空闲连接数
        max-idle: 200
        min-idle: 5

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seckill?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456

    hikari:
      # 连接池名称
      pool-name: DateHikariCP
      # 最小空闲连接数
      minimum-idle: 5
      # 空闲连接最大存活时间，默认600_000(10分钟)
      idle-timeout: 180000
      # 最大连接数，默认10
      maximum-pool-size: 10
      # 事务自动提交
      auto-commit: true
      # 连接最大存活时间，默认1_800_000(30分钟)
      max-lifetime: 1800000
      # 连接超时时间，默认30_000(30秒)
      connection-timeout: 30000
      # 连接测试语句
      connection-test-query: SELECT 1

mybatis-plus:
  # Mapper映射文件
  mapper-locations: classpath*:/mapper/*Mapper.xml
  # Mybatis数据返回类型，默认别名为类名
  type-aliases-package: cn.iris.seckill.pojo

logging:
  level:
    # mapper方法接口打印
    cn.iris.seckill.mapper: debug